<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
>
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example.openrewrite</groupId>
  <artifactId>openrewrite-java-modernization-lab</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>apps/boot-27-to-3x</module>
    <module>apps/java-8-to-17</module>
    <module>apps/spring-5-to-6</module>
  </modules>
</project>
